CUDA_VISIBLE_DEVICES=0 python cnn_1conv_1fc_snd_img.py
CUDA_VISIBLE_DEVICES=1 python cnn_1conv_2fc_snd_img.py
CUDA_VISIBLE_DEVICES=2 python cnn_2conv_1fc_snd_img.py
CUDA_VISIBLE_DEVICES=3 python cnn_2conv_2fc_snd_img.py
CUDA_VISIBLE_DEVICES=4 python cnn_3conv_1fc_snd_img.py
CUDA_VISIBLE_DEVICES=5 python cnn_3conv_2fc_snd_img.py
CUDA_VISIBLE_DEVICES=6 python cnn_4conv_1fc_snd_img.py
CUDA_VISIBLE_DEVICES=7 python cnn_4conv_2fc_snd_img.py

CUDA_VISIBLE_DEVICES=0 python cnn_5conv_1fc_snd_img.py
CUDA_VISIBLE_DEVICES=1 python cnn_5conv_2fc_snd_img.py
CUDA_VISIBLE_DEVICES=2 python cnn_6conv_1fc_snd_img.py
CUDA_VISIBLE_DEVICES=3 python cnn_6conv_2fc_snd_img.py
